// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	experiment "github.com/drakoRRR/ab-test-system/apps/ab-test-system/backend/internal/domain/experiment"

	uuid "github.com/google/uuid"
)

// MockExperimentStorage is an autogenerated mock type for the ExperimentStorage type
type MockExperimentStorage struct {
	mock.Mock
}

type MockExperimentStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExperimentStorage) EXPECT() *MockExperimentStorage_Expecter {
	return &MockExperimentStorage_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, projectID, experimentID
func (_m *MockExperimentStorage) GetByID(ctx context.Context, projectID uuid.UUID, experimentID uuid.UUID) (experiment.Experiment, error) {
	ret := _m.Called(ctx, projectID, experimentID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 experiment.Experiment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (experiment.Experiment, error)); ok {
		return rf(ctx, projectID, experimentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) experiment.Experiment); ok {
		r0 = rf(ctx, projectID, experimentID)
	} else {
		r0 = ret.Get(0).(experiment.Experiment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, projectID, experimentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExperimentStorage_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockExperimentStorage_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
//   - experimentID uuid.UUID
func (_e *MockExperimentStorage_Expecter) GetByID(ctx interface{}, projectID interface{}, experimentID interface{}) *MockExperimentStorage_GetByID_Call {
	return &MockExperimentStorage_GetByID_Call{Call: _e.mock.On("GetByID", ctx, projectID, experimentID)}
}

func (_c *MockExperimentStorage_GetByID_Call) Run(run func(ctx context.Context, projectID uuid.UUID, experimentID uuid.UUID)) *MockExperimentStorage_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockExperimentStorage_GetByID_Call) Return(_a0 experiment.Experiment, _a1 error) *MockExperimentStorage_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExperimentStorage_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (experiment.Experiment, error)) *MockExperimentStorage_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExperimentStorage creates a new instance of MockExperimentStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExperimentStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExperimentStorage {
	mock := &MockExperimentStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
