// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package main

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMocksdkClient creates a new instance of MocksdkClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocksdkClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MocksdkClient {
	mock := &MocksdkClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MocksdkClient is an autogenerated mock type for the sdkClient type
type MocksdkClient struct {
	mock.Mock
}

type MocksdkClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MocksdkClient) EXPECT() *MocksdkClient_Expecter {
	return &MocksdkClient_Expecter{mock: &_m.Mock}
}

// GetVariant provides a mock function for the type MocksdkClient
func (_mock *MocksdkClient) GetVariant(experimentKey string, userID string) string {
	ret := _mock.Called(experimentKey, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetVariant")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(experimentKey, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MocksdkClient_GetVariant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVariant'
type MocksdkClient_GetVariant_Call struct {
	*mock.Call
}

// GetVariant is a helper method to define mock.On call
//   - experimentKey string
//   - userID string
func (_e *MocksdkClient_Expecter) GetVariant(experimentKey interface{}, userID interface{}) *MocksdkClient_GetVariant_Call {
	return &MocksdkClient_GetVariant_Call{Call: _e.mock.On("GetVariant", experimentKey, userID)}
}

func (_c *MocksdkClient_GetVariant_Call) Run(run func(experimentKey string, userID string)) *MocksdkClient_GetVariant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MocksdkClient_GetVariant_Call) Return(s string) *MocksdkClient_GetVariant_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MocksdkClient_GetVariant_Call) RunAndReturn(run func(experimentKey string, userID string) string) *MocksdkClient_GetVariant_Call {
	_c.Call.Return(run)
	return _c
}

// IsEnabled provides a mock function for the type MocksdkClient
func (_mock *MocksdkClient) IsEnabled(flagKey string, userID string) bool {
	ret := _mock.Called(flagKey, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsEnabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(flagKey, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MocksdkClient_IsEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEnabled'
type MocksdkClient_IsEnabled_Call struct {
	*mock.Call
}

// IsEnabled is a helper method to define mock.On call
//   - flagKey string
//   - userID string
func (_e *MocksdkClient_Expecter) IsEnabled(flagKey interface{}, userID interface{}) *MocksdkClient_IsEnabled_Call {
	return &MocksdkClient_IsEnabled_Call{Call: _e.mock.On("IsEnabled", flagKey, userID)}
}

func (_c *MocksdkClient_IsEnabled_Call) Run(run func(flagKey string, userID string)) *MocksdkClient_IsEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MocksdkClient_IsEnabled_Call) Return(b bool) *MocksdkClient_IsEnabled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MocksdkClient_IsEnabled_Call) RunAndReturn(run func(flagKey string, userID string) bool) *MocksdkClient_IsEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// Track provides a mock function for the type MocksdkClient
func (_mock *MocksdkClient) Track(eventName string, userID string, value float64) {
	_mock.Called(eventName, userID, value)
	return
}

// MocksdkClient_Track_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Track'
type MocksdkClient_Track_Call struct {
	*mock.Call
}

// Track is a helper method to define mock.On call
//   - eventName string
//   - userID string
//   - value float64
func (_e *MocksdkClient_Expecter) Track(eventName interface{}, userID interface{}, value interface{}) *MocksdkClient_Track_Call {
	return &MocksdkClient_Track_Call{Call: _e.mock.On("Track", eventName, userID, value)}
}

func (_c *MocksdkClient_Track_Call) Run(run func(eventName string, userID string, value float64)) *MocksdkClient_Track_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MocksdkClient_Track_Call) Return() *MocksdkClient_Track_Call {
	_c.Call.Return()
	return _c
}

func (_c *MocksdkClient_Track_Call) RunAndReturn(run func(eventName string, userID string, value float64)) *MocksdkClient_Track_Call {
	_c.Run(run)
	return _c
}
