// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	user "github.com/drakoRRR/ab-test-system/apps/ab-test-system/backend/internal/domain/user"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// GetByFirebaseUID provides a mock function with given fields: ctx, uid
func (_m *MockStorage) GetByFirebaseUID(ctx context.Context, uid string) (user.User, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for GetByFirebaseUID")
	}

	var r0 user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (user.User, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) user.User); ok {
		r0 = rf(ctx, uid)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetByFirebaseUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByFirebaseUID'
type MockStorage_GetByFirebaseUID_Call struct {
	*mock.Call
}

// GetByFirebaseUID is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *MockStorage_Expecter) GetByFirebaseUID(ctx interface{}, uid interface{}) *MockStorage_GetByFirebaseUID_Call {
	return &MockStorage_GetByFirebaseUID_Call{Call: _e.mock.On("GetByFirebaseUID", ctx, uid)}
}

func (_c *MockStorage_GetByFirebaseUID_Call) Run(run func(ctx context.Context, uid string)) *MockStorage_GetByFirebaseUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_GetByFirebaseUID_Call) Return(_a0 user.User, _a1 error) *MockStorage_GetByFirebaseUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetByFirebaseUID_Call) RunAndReturn(run func(context.Context, string) (user.User, error)) *MockStorage_GetByFirebaseUID_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, u
func (_m *MockStorage) Upsert(ctx context.Context, u user.User) (user.User, error) {
	ret := _m.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.User) (user.User, error)); ok {
		return rf(ctx, u)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.User) user.User); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.User) error); ok {
		r1 = rf(ctx, u)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockStorage_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - u user.User
func (_e *MockStorage_Expecter) Upsert(ctx interface{}, u interface{}) *MockStorage_Upsert_Call {
	return &MockStorage_Upsert_Call{Call: _e.mock.On("Upsert", ctx, u)}
}

func (_c *MockStorage_Upsert_Call) Run(run func(ctx context.Context, u user.User)) *MockStorage_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(user.User))
	})
	return _c
}

func (_c *MockStorage_Upsert_Call) Return(_a0 user.User, _a1 error) *MockStorage_Upsert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_Upsert_Call) RunAndReturn(run func(context.Context, user.User) (user.User, error)) *MockStorage_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
