// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	flag "github.com/drakoRRR/ab-test-system/apps/ab-test-system/backend/internal/domain/flag"

	uuid "github.com/google/uuid"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, f
func (_m *MockStorage) Create(ctx context.Context, f flag.Flag) (flag.Flag, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 flag.Flag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, flag.Flag) (flag.Flag, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, flag.Flag) flag.Flag); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Get(0).(flag.Flag)
	}

	if rf, ok := ret.Get(1).(func(context.Context, flag.Flag) error); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStorage_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - f flag.Flag
func (_e *MockStorage_Expecter) Create(ctx interface{}, f interface{}) *MockStorage_Create_Call {
	return &MockStorage_Create_Call{Call: _e.mock.On("Create", ctx, f)}
}

func (_c *MockStorage_Create_Call) Run(run func(ctx context.Context, f flag.Flag)) *MockStorage_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(flag.Flag))
	})
	return _c
}

func (_c *MockStorage_Create_Call) Return(_a0 flag.Flag, _a1 error) *MockStorage_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_Create_Call) RunAndReturn(run func(context.Context, flag.Flag) (flag.Flag, error)) *MockStorage_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, projectID, key
func (_m *MockStorage) Delete(ctx context.Context, projectID uuid.UUID, key string) error {
	ret := _m.Called(ctx, projectID, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, projectID, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
//   - key string
func (_e *MockStorage_Expecter) Delete(ctx interface{}, projectID interface{}, key interface{}) *MockStorage_Delete_Call {
	return &MockStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, projectID, key)}
}

func (_c *MockStorage_Delete_Call) Run(run func(ctx context.Context, projectID uuid.UUID, key string)) *MockStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockStorage_Delete_Call) Return(_a0 error) *MockStorage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByKey provides a mock function with given fields: ctx, projectID, key
func (_m *MockStorage) GetByKey(ctx context.Context, projectID uuid.UUID, key string) (flag.Flag, error) {
	ret := _m.Called(ctx, projectID, key)

	if len(ret) == 0 {
		panic("no return value specified for GetByKey")
	}

	var r0 flag.Flag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (flag.Flag, error)); ok {
		return rf(ctx, projectID, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) flag.Flag); ok {
		r0 = rf(ctx, projectID, key)
	} else {
		r0 = ret.Get(0).(flag.Flag)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, projectID, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByKey'
type MockStorage_GetByKey_Call struct {
	*mock.Call
}

// GetByKey is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
//   - key string
func (_e *MockStorage_Expecter) GetByKey(ctx interface{}, projectID interface{}, key interface{}) *MockStorage_GetByKey_Call {
	return &MockStorage_GetByKey_Call{Call: _e.mock.On("GetByKey", ctx, projectID, key)}
}

func (_c *MockStorage_GetByKey_Call) Run(run func(ctx context.Context, projectID uuid.UUID, key string)) *MockStorage_GetByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockStorage_GetByKey_Call) Return(_a0 flag.Flag, _a1 error) *MockStorage_GetByKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetByKey_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (flag.Flag, error)) *MockStorage_GetByKey_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, projectID
func (_m *MockStorage) List(ctx context.Context, projectID uuid.UUID) ([]flag.Flag, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []flag.Flag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]flag.Flag, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []flag.Flag); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]flag.Flag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockStorage_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
func (_e *MockStorage_Expecter) List(ctx interface{}, projectID interface{}) *MockStorage_List_Call {
	return &MockStorage_List_Call{Call: _e.mock.On("List", ctx, projectID)}
}

func (_c *MockStorage_List_Call) Run(run func(ctx context.Context, projectID uuid.UUID)) *MockStorage_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStorage_List_Call) Return(_a0 []flag.Flag, _a1 error) *MockStorage_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_List_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]flag.Flag, error)) *MockStorage_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, f
func (_m *MockStorage) Update(ctx context.Context, f flag.Flag) (flag.Flag, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 flag.Flag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, flag.Flag) (flag.Flag, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, flag.Flag) flag.Flag); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Get(0).(flag.Flag)
	}

	if rf, ok := ret.Get(1).(func(context.Context, flag.Flag) error); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockStorage_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - f flag.Flag
func (_e *MockStorage_Expecter) Update(ctx interface{}, f interface{}) *MockStorage_Update_Call {
	return &MockStorage_Update_Call{Call: _e.mock.On("Update", ctx, f)}
}

func (_c *MockStorage_Update_Call) Run(run func(ctx context.Context, f flag.Flag)) *MockStorage_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(flag.Flag))
	})
	return _c
}

func (_c *MockStorage_Update_Call) Return(_a0 flag.Flag, _a1 error) *MockStorage_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_Update_Call) RunAndReturn(run func(context.Context, flag.Flag) (flag.Flag, error)) *MockStorage_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
