// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	flag "github.com/drakoRRR/ab-test-system/apps/ab-test-system/backend/internal/domain/flag"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, projectID, key, name
func (_m *MockService) Create(ctx context.Context, projectID uuid.UUID, key string, name string) (flag.Flag, error) {
	ret := _m.Called(ctx, projectID, key, name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 flag.Flag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (flag.Flag, error)); ok {
		return rf(ctx, projectID, key, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) flag.Flag); ok {
		r0 = rf(ctx, projectID, key, name)
	} else {
		r0 = ret.Get(0).(flag.Flag)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, projectID, key, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
//   - key string
//   - name string
func (_e *MockService_Expecter) Create(ctx interface{}, projectID interface{}, key interface{}, name interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, projectID, key, name)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, projectID uuid.UUID, key string, name string)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockService_Create_Call) Return(_a0 flag.Flag, _a1 error) *MockService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string) (flag.Flag, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, projectID, key
func (_m *MockService) Delete(ctx context.Context, projectID uuid.UUID, key string) error {
	ret := _m.Called(ctx, projectID, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, projectID, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
//   - key string
func (_e *MockService_Expecter) Delete(ctx interface{}, projectID interface{}, key interface{}) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", ctx, projectID, key)}
}

func (_c *MockService_Delete_Call) Run(run func(ctx context.Context, projectID uuid.UUID, key string)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(_a0 error) *MockService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByKey provides a mock function with given fields: ctx, projectID, key
func (_m *MockService) GetByKey(ctx context.Context, projectID uuid.UUID, key string) (flag.Flag, error) {
	ret := _m.Called(ctx, projectID, key)

	if len(ret) == 0 {
		panic("no return value specified for GetByKey")
	}

	var r0 flag.Flag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (flag.Flag, error)); ok {
		return rf(ctx, projectID, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) flag.Flag); ok {
		r0 = rf(ctx, projectID, key)
	} else {
		r0 = ret.Get(0).(flag.Flag)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, projectID, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByKey'
type MockService_GetByKey_Call struct {
	*mock.Call
}

// GetByKey is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
//   - key string
func (_e *MockService_Expecter) GetByKey(ctx interface{}, projectID interface{}, key interface{}) *MockService_GetByKey_Call {
	return &MockService_GetByKey_Call{Call: _e.mock.On("GetByKey", ctx, projectID, key)}
}

func (_c *MockService_GetByKey_Call) Run(run func(ctx context.Context, projectID uuid.UUID, key string)) *MockService_GetByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetByKey_Call) Return(_a0 flag.Flag, _a1 error) *MockService_GetByKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetByKey_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (flag.Flag, error)) *MockService_GetByKey_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, projectID
func (_m *MockService) List(ctx context.Context, projectID uuid.UUID) ([]flag.Flag, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []flag.Flag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]flag.Flag, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []flag.Flag); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]flag.Flag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
func (_e *MockService_Expecter) List(ctx interface{}, projectID interface{}) *MockService_List_Call {
	return &MockService_List_Call{Call: _e.mock.On("List", ctx, projectID)}
}

func (_c *MockService_List_Call) Run(run func(ctx context.Context, projectID uuid.UUID)) *MockService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_List_Call) Return(_a0 []flag.Flag, _a1 error) *MockService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_List_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]flag.Flag, error)) *MockService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, p
func (_m *MockService) Update(ctx context.Context, p flag.UpdateParams) (flag.Flag, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 flag.Flag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, flag.UpdateParams) (flag.Flag, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, flag.UpdateParams) flag.Flag); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(flag.Flag)
	}

	if rf, ok := ret.Get(1).(func(context.Context, flag.UpdateParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - p flag.UpdateParams
func (_e *MockService_Expecter) Update(ctx interface{}, p interface{}) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", ctx, p)}
}

func (_c *MockService_Update_Call) Run(run func(ctx context.Context, p flag.UpdateParams)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(flag.UpdateParams))
	})
	return _c
}

func (_c *MockService_Update_Call) Return(_a0 flag.Flag, _a1 error) *MockService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(context.Context, flag.UpdateParams) (flag.Flag, error)) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
