version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - govet
    - ineffassign
    - noctx
    - staticcheck
    - unconvert
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
