// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	analytics "github.com/drakoRRR/ab-test-system/apps/ab-test-system/backend/internal/domain/analytics"

	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetResult provides a mock function with given fields: ctx, projectID, experimentID
func (_m *MockService) GetResult(ctx context.Context, projectID uuid.UUID, experimentID uuid.UUID) (analytics.ExperimentResult, error) {
	ret := _m.Called(ctx, projectID, experimentID)

	if len(ret) == 0 {
		panic("no return value specified for GetResult")
	}

	var r0 analytics.ExperimentResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (analytics.ExperimentResult, error)); ok {
		return rf(ctx, projectID, experimentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) analytics.ExperimentResult); ok {
		r0 = rf(ctx, projectID, experimentID)
	} else {
		r0 = ret.Get(0).(analytics.ExperimentResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, projectID, experimentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResult'
type MockService_GetResult_Call struct {
	*mock.Call
}

// GetResult is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
//   - experimentID uuid.UUID
func (_e *MockService_Expecter) GetResult(ctx interface{}, projectID interface{}, experimentID interface{}) *MockService_GetResult_Call {
	return &MockService_GetResult_Call{Call: _e.mock.On("GetResult", ctx, projectID, experimentID)}
}

func (_c *MockService_GetResult_Call) Run(run func(ctx context.Context, projectID uuid.UUID, experimentID uuid.UUID)) *MockService_GetResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_GetResult_Call) Return(_a0 analytics.ExperimentResult, _a1 error) *MockService_GetResult_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetResult_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (analytics.ExperimentResult, error)) *MockService_GetResult_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
