// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	apikey "github.com/drakoRRR/ab-test-system/apps/ab-test-system/backend/internal/domain/apikey"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, key
func (_m *MockStorage) Create(ctx context.Context, key apikey.Key) (apikey.Key, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 apikey.Key
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, apikey.Key) (apikey.Key, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, apikey.Key) apikey.Key); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(apikey.Key)
	}

	if rf, ok := ret.Get(1).(func(context.Context, apikey.Key) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStorage_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - key apikey.Key
func (_e *MockStorage_Expecter) Create(ctx interface{}, key interface{}) *MockStorage_Create_Call {
	return &MockStorage_Create_Call{Call: _e.mock.On("Create", ctx, key)}
}

func (_c *MockStorage_Create_Call) Run(run func(ctx context.Context, key apikey.Key)) *MockStorage_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(apikey.Key))
	})
	return _c
}

func (_c *MockStorage_Create_Call) Return(_a0 apikey.Key, _a1 error) *MockStorage_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_Create_Call) RunAndReturn(run func(context.Context, apikey.Key) (apikey.Key, error)) *MockStorage_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByKeyHash provides a mock function with given fields: ctx, keyHash
func (_m *MockStorage) GetByKeyHash(ctx context.Context, keyHash string) (apikey.Key, error) {
	ret := _m.Called(ctx, keyHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByKeyHash")
	}

	var r0 apikey.Key
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (apikey.Key, error)); ok {
		return rf(ctx, keyHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) apikey.Key); ok {
		r0 = rf(ctx, keyHash)
	} else {
		r0 = ret.Get(0).(apikey.Key)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, keyHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetByKeyHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByKeyHash'
type MockStorage_GetByKeyHash_Call struct {
	*mock.Call
}

// GetByKeyHash is a helper method to define mock.On call
//   - ctx context.Context
//   - keyHash string
func (_e *MockStorage_Expecter) GetByKeyHash(ctx interface{}, keyHash interface{}) *MockStorage_GetByKeyHash_Call {
	return &MockStorage_GetByKeyHash_Call{Call: _e.mock.On("GetByKeyHash", ctx, keyHash)}
}

func (_c *MockStorage_GetByKeyHash_Call) Run(run func(ctx context.Context, keyHash string)) *MockStorage_GetByKeyHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_GetByKeyHash_Call) Return(_a0 apikey.Key, _a1 error) *MockStorage_GetByKeyHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetByKeyHash_Call) RunAndReturn(run func(context.Context, string) (apikey.Key, error)) *MockStorage_GetByKeyHash_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, projectID
func (_m *MockStorage) List(ctx context.Context, projectID uuid.UUID) ([]apikey.Key, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []apikey.Key
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]apikey.Key, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []apikey.Key); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]apikey.Key)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockStorage_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
func (_e *MockStorage_Expecter) List(ctx interface{}, projectID interface{}) *MockStorage_List_Call {
	return &MockStorage_List_Call{Call: _e.mock.On("List", ctx, projectID)}
}

func (_c *MockStorage_List_Call) Run(run func(ctx context.Context, projectID uuid.UUID)) *MockStorage_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStorage_List_Call) Return(_a0 []apikey.Key, _a1 error) *MockStorage_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_List_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]apikey.Key, error)) *MockStorage_List_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, id, projectID
func (_m *MockStorage) Revoke(ctx context.Context, id uuid.UUID, projectID uuid.UUID) error {
	ret := _m.Called(ctx, id, projectID)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, id, projectID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockStorage_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - projectID uuid.UUID
func (_e *MockStorage_Expecter) Revoke(ctx interface{}, id interface{}, projectID interface{}) *MockStorage_Revoke_Call {
	return &MockStorage_Revoke_Call{Call: _e.mock.On("Revoke", ctx, id, projectID)}
}

func (_c *MockStorage_Revoke_Call) Run(run func(ctx context.Context, id uuid.UUID, projectID uuid.UUID)) *MockStorage_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockStorage_Revoke_Call) Return(_a0 error) *MockStorage_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Revoke_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockStorage_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
