// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	project "github.com/drakoRRR/ab-test-system/apps/ab-test-system/backend/internal/domain/project"

	uuid "github.com/google/uuid"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, p
func (_m *MockStorage) Create(ctx context.Context, p project.Project) (project.Project, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 project.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, project.Project) (project.Project, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, project.Project) project.Project); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(project.Project)
	}

	if rf, ok := ret.Get(1).(func(context.Context, project.Project) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStorage_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p project.Project
func (_e *MockStorage_Expecter) Create(ctx interface{}, p interface{}) *MockStorage_Create_Call {
	return &MockStorage_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *MockStorage_Create_Call) Run(run func(ctx context.Context, p project.Project)) *MockStorage_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(project.Project))
	})
	return _c
}

func (_c *MockStorage_Create_Call) Return(_a0 project.Project, _a1 error) *MockStorage_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_Create_Call) RunAndReturn(run func(context.Context, project.Project) (project.Project, error)) *MockStorage_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id, orgID
func (_m *MockStorage) Delete(ctx context.Context, id uuid.UUID, orgID uuid.UUID) error {
	ret := _m.Called(ctx, id, orgID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, id, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - orgID uuid.UUID
func (_e *MockStorage_Expecter) Delete(ctx interface{}, id interface{}, orgID interface{}) *MockStorage_Delete_Call {
	return &MockStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, id, orgID)}
}

func (_c *MockStorage_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID, orgID uuid.UUID)) *MockStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockStorage_Delete_Call) Return(_a0 error) *MockStorage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id, orgID
func (_m *MockStorage) GetByID(ctx context.Context, id uuid.UUID, orgID uuid.UUID) (project.Project, error) {
	ret := _m.Called(ctx, id, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 project.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (project.Project, error)); ok {
		return rf(ctx, id, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) project.Project); ok {
		r0 = rf(ctx, id, orgID)
	} else {
		r0 = ret.Get(0).(project.Project)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, id, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockStorage_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - orgID uuid.UUID
func (_e *MockStorage_Expecter) GetByID(ctx interface{}, id interface{}, orgID interface{}) *MockStorage_GetByID_Call {
	return &MockStorage_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id, orgID)}
}

func (_c *MockStorage_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID, orgID uuid.UUID)) *MockStorage_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockStorage_GetByID_Call) Return(_a0 project.Project, _a1 error) *MockStorage_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (project.Project, error)) *MockStorage_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, orgID
func (_m *MockStorage) List(ctx context.Context, orgID uuid.UUID) ([]project.Project, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []project.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]project.Project, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []project.Project); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]project.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockStorage_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
func (_e *MockStorage_Expecter) List(ctx interface{}, orgID interface{}) *MockStorage_List_Call {
	return &MockStorage_List_Call{Call: _e.mock.On("List", ctx, orgID)}
}

func (_c *MockStorage_List_Call) Run(run func(ctx context.Context, orgID uuid.UUID)) *MockStorage_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStorage_List_Call) Return(_a0 []project.Project, _a1 error) *MockStorage_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_List_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]project.Project, error)) *MockStorage_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, p
func (_m *MockStorage) Update(ctx context.Context, p project.Project) (project.Project, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 project.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, project.Project) (project.Project, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, project.Project) project.Project); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(project.Project)
	}

	if rf, ok := ret.Get(1).(func(context.Context, project.Project) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockStorage_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - p project.Project
func (_e *MockStorage_Expecter) Update(ctx interface{}, p interface{}) *MockStorage_Update_Call {
	return &MockStorage_Update_Call{Call: _e.mock.On("Update", ctx, p)}
}

func (_c *MockStorage_Update_Call) Run(run func(ctx context.Context, p project.Project)) *MockStorage_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(project.Project))
	})
	return _c
}

func (_c *MockStorage_Update_Call) Return(_a0 project.Project, _a1 error) *MockStorage_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_Update_Call) RunAndReturn(run func(context.Context, project.Project) (project.Project, error)) *MockStorage_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
