// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	user "github.com/drakoRRR/ab-test-system/apps/ab-test-system/backend/internal/domain/user"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateOrUpdate provides a mock function with given fields: ctx, firebaseUID, email, name, photoURL
func (_m *MockService) CreateOrUpdate(ctx context.Context, firebaseUID string, email string, name string, photoURL *string) (user.User, error) {
	ret := _m.Called(ctx, firebaseUID, email, name, photoURL)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdate")
	}

	var r0 user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *string) (user.User, error)); ok {
		return rf(ctx, firebaseUID, email, name, photoURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *string) user.User); ok {
		r0 = rf(ctx, firebaseUID, email, name, photoURL)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, *string) error); ok {
		r1 = rf(ctx, firebaseUID, email, name, photoURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateOrUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdate'
type MockService_CreateOrUpdate_Call struct {
	*mock.Call
}

// CreateOrUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - firebaseUID string
//   - email string
//   - name string
//   - photoURL *string
func (_e *MockService_Expecter) CreateOrUpdate(ctx interface{}, firebaseUID interface{}, email interface{}, name interface{}, photoURL interface{}) *MockService_CreateOrUpdate_Call {
	return &MockService_CreateOrUpdate_Call{Call: _e.mock.On("CreateOrUpdate", ctx, firebaseUID, email, name, photoURL)}
}

func (_c *MockService_CreateOrUpdate_Call) Run(run func(ctx context.Context, firebaseUID string, email string, name string, photoURL *string)) *MockService_CreateOrUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(*string))
	})
	return _c
}

func (_c *MockService_CreateOrUpdate_Call) Return(_a0 user.User, _a1 error) *MockService_CreateOrUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateOrUpdate_Call) RunAndReturn(run func(context.Context, string, string, string, *string) (user.User, error)) *MockService_CreateOrUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentUser provides a mock function with given fields: ctx, firebaseUID
func (_m *MockService) GetCurrentUser(ctx context.Context, firebaseUID string) (user.User, error) {
	ret := _m.Called(ctx, firebaseUID)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentUser")
	}

	var r0 user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (user.User, error)); ok {
		return rf(ctx, firebaseUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) user.User); ok {
		r0 = rf(ctx, firebaseUID)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, firebaseUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetCurrentUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentUser'
type MockService_GetCurrentUser_Call struct {
	*mock.Call
}

// GetCurrentUser is a helper method to define mock.On call
//   - ctx context.Context
//   - firebaseUID string
func (_e *MockService_Expecter) GetCurrentUser(ctx interface{}, firebaseUID interface{}) *MockService_GetCurrentUser_Call {
	return &MockService_GetCurrentUser_Call{Call: _e.mock.On("GetCurrentUser", ctx, firebaseUID)}
}

func (_c *MockService_GetCurrentUser_Call) Run(run func(ctx context.Context, firebaseUID string)) *MockService_GetCurrentUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_GetCurrentUser_Call) Return(_a0 user.User, _a1 error) *MockService_GetCurrentUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetCurrentUser_Call) RunAndReturn(run func(context.Context, string) (user.User, error)) *MockService_GetCurrentUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
