// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	project "github.com/drakoRRR/ab-test-system/apps/ab-test-system/backend/internal/domain/project"
)

// MockProjectService is an autogenerated mock type for the ProjectService type
type MockProjectService struct {
	mock.Mock
}

type MockProjectService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectService) EXPECT() *MockProjectService_Expecter {
	return &MockProjectService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, orgID, name, description
func (_m *MockProjectService) Create(ctx context.Context, orgID uuid.UUID, name string, description string) (project.Project, error) {
	ret := _m.Called(ctx, orgID, name, description)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 project.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (project.Project, error)); ok {
		return rf(ctx, orgID, name, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) project.Project); ok {
		r0 = rf(ctx, orgID, name, description)
	} else {
		r0 = ret.Get(0).(project.Project)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, orgID, name, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProjectService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - name string
//   - description string
func (_e *MockProjectService_Expecter) Create(ctx interface{}, orgID interface{}, name interface{}, description interface{}) *MockProjectService_Create_Call {
	return &MockProjectService_Create_Call{Call: _e.mock.On("Create", ctx, orgID, name, description)}
}

func (_c *MockProjectService_Create_Call) Run(run func(ctx context.Context, orgID uuid.UUID, name string, description string)) *MockProjectService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockProjectService_Create_Call) Return(_a0 project.Project, _a1 error) *MockProjectService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectService_Create_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string) (project.Project, error)) *MockProjectService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, orgID, projectID
func (_m *MockProjectService) Delete(ctx context.Context, orgID uuid.UUID, projectID uuid.UUID) error {
	ret := _m.Called(ctx, orgID, projectID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, orgID, projectID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProjectService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProjectService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - projectID uuid.UUID
func (_e *MockProjectService_Expecter) Delete(ctx interface{}, orgID interface{}, projectID interface{}) *MockProjectService_Delete_Call {
	return &MockProjectService_Delete_Call{Call: _e.mock.On("Delete", ctx, orgID, projectID)}
}

func (_c *MockProjectService_Delete_Call) Run(run func(ctx context.Context, orgID uuid.UUID, projectID uuid.UUID)) *MockProjectService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockProjectService_Delete_Call) Return(_a0 error) *MockProjectService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProjectService_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockProjectService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, orgID, projectID
func (_m *MockProjectService) GetByID(ctx context.Context, orgID uuid.UUID, projectID uuid.UUID) (project.Project, error) {
	ret := _m.Called(ctx, orgID, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 project.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (project.Project, error)); ok {
		return rf(ctx, orgID, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) project.Project); ok {
		r0 = rf(ctx, orgID, projectID)
	} else {
		r0 = ret.Get(0).(project.Project)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockProjectService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - projectID uuid.UUID
func (_e *MockProjectService_Expecter) GetByID(ctx interface{}, orgID interface{}, projectID interface{}) *MockProjectService_GetByID_Call {
	return &MockProjectService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, orgID, projectID)}
}

func (_c *MockProjectService_GetByID_Call) Run(run func(ctx context.Context, orgID uuid.UUID, projectID uuid.UUID)) *MockProjectService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockProjectService_GetByID_Call) Return(_a0 project.Project, _a1 error) *MockProjectService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectService_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (project.Project, error)) *MockProjectService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, orgID
func (_m *MockProjectService) List(ctx context.Context, orgID uuid.UUID) ([]project.Project, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []project.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]project.Project, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []project.Project); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]project.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockProjectService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
func (_e *MockProjectService_Expecter) List(ctx interface{}, orgID interface{}) *MockProjectService_List_Call {
	return &MockProjectService_List_Call{Call: _e.mock.On("List", ctx, orgID)}
}

func (_c *MockProjectService_List_Call) Run(run func(ctx context.Context, orgID uuid.UUID)) *MockProjectService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProjectService_List_Call) Return(_a0 []project.Project, _a1 error) *MockProjectService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectService_List_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]project.Project, error)) *MockProjectService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, orgID, projectID, name, description
func (_m *MockProjectService) Update(ctx context.Context, orgID uuid.UUID, projectID uuid.UUID, name *string, description *string) (project.Project, error) {
	ret := _m.Called(ctx, orgID, projectID, name, description)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 project.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *string, *string) (project.Project, error)); ok {
		return rf(ctx, orgID, projectID, name, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *string, *string) project.Project); ok {
		r0 = rf(ctx, orgID, projectID, name, description)
	} else {
		r0 = ret.Get(0).(project.Project)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, *string, *string) error); ok {
		r1 = rf(ctx, orgID, projectID, name, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProjectService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - projectID uuid.UUID
//   - name *string
//   - description *string
func (_e *MockProjectService_Expecter) Update(ctx interface{}, orgID interface{}, projectID interface{}, name interface{}, description interface{}) *MockProjectService_Update_Call {
	return &MockProjectService_Update_Call{Call: _e.mock.On("Update", ctx, orgID, projectID, name, description)}
}

func (_c *MockProjectService_Update_Call) Run(run func(ctx context.Context, orgID uuid.UUID, projectID uuid.UUID, name *string, description *string)) *MockProjectService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(*string), args[4].(*string))
	})
	return _c
}

func (_c *MockProjectService_Update_Call) Return(_a0 project.Project, _a1 error) *MockProjectService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectService_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, *string, *string) (project.Project, error)) *MockProjectService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectService creates a new instance of MockProjectService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectService {
	mock := &MockProjectService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
