// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	user "github.com/drakoRRR/ab-test-system/apps/ab-test-system/backend/internal/domain/user"
)

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// GetCurrentUser provides a mock function with given fields: ctx, firebaseUID
func (_m *MockUserService) GetCurrentUser(ctx context.Context, firebaseUID string) (user.User, error) {
	ret := _m.Called(ctx, firebaseUID)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentUser")
	}

	var r0 user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (user.User, error)); ok {
		return rf(ctx, firebaseUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) user.User); ok {
		r0 = rf(ctx, firebaseUID)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, firebaseUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_GetCurrentUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentUser'
type MockUserService_GetCurrentUser_Call struct {
	*mock.Call
}

// GetCurrentUser is a helper method to define mock.On call
//   - ctx context.Context
//   - firebaseUID string
func (_e *MockUserService_Expecter) GetCurrentUser(ctx interface{}, firebaseUID interface{}) *MockUserService_GetCurrentUser_Call {
	return &MockUserService_GetCurrentUser_Call{Call: _e.mock.On("GetCurrentUser", ctx, firebaseUID)}
}

func (_c *MockUserService_GetCurrentUser_Call) Run(run func(ctx context.Context, firebaseUID string)) *MockUserService_GetCurrentUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserService_GetCurrentUser_Call) Return(_a0 user.User, _a1 error) *MockUserService_GetCurrentUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_GetCurrentUser_Call) RunAndReturn(run func(context.Context, string) (user.User, error)) *MockUserService_GetCurrentUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
