// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	flag "github.com/drakoRRR/ab-test-system/apps/ab-test-system/backend/internal/domain/flag"

	uuid "github.com/google/uuid"
)

// MockFlagLister is an autogenerated mock type for the FlagLister type
type MockFlagLister struct {
	mock.Mock
}

type MockFlagLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFlagLister) EXPECT() *MockFlagLister_Expecter {
	return &MockFlagLister_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: ctx, projectID
func (_m *MockFlagLister) List(ctx context.Context, projectID uuid.UUID) ([]flag.Flag, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []flag.Flag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]flag.Flag, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []flag.Flag); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]flag.Flag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFlagLister_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockFlagLister_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
func (_e *MockFlagLister_Expecter) List(ctx interface{}, projectID interface{}) *MockFlagLister_List_Call {
	return &MockFlagLister_List_Call{Call: _e.mock.On("List", ctx, projectID)}
}

func (_c *MockFlagLister_List_Call) Run(run func(ctx context.Context, projectID uuid.UUID)) *MockFlagLister_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockFlagLister_List_Call) Return(_a0 []flag.Flag, _a1 error) *MockFlagLister_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFlagLister_List_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]flag.Flag, error)) *MockFlagLister_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFlagLister creates a new instance of MockFlagLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFlagLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFlagLister {
	mock := &MockFlagLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
