// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	analytics "github.com/drakoRRR/ab-test-system/apps/ab-test-system/backend/internal/domain/analytics"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockMetricsStorage is an autogenerated mock type for the MetricsStorage type
type MockMetricsStorage struct {
	mock.Mock
}

type MockMetricsStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsStorage) EXPECT() *MockMetricsStorage_Expecter {
	return &MockMetricsStorage_Expecter{mock: &_m.Mock}
}

// GetMetrics provides a mock function with given fields: ctx, experimentID
func (_m *MockMetricsStorage) GetMetrics(ctx context.Context, experimentID uuid.UUID) ([]analytics.VariantMetrics, error) {
	ret := _m.Called(ctx, experimentID)

	if len(ret) == 0 {
		panic("no return value specified for GetMetrics")
	}

	var r0 []analytics.VariantMetrics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]analytics.VariantMetrics, error)); ok {
		return rf(ctx, experimentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []analytics.VariantMetrics); ok {
		r0 = rf(ctx, experimentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]analytics.VariantMetrics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, experimentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMetricsStorage_GetMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetrics'
type MockMetricsStorage_GetMetrics_Call struct {
	*mock.Call
}

// GetMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - experimentID uuid.UUID
func (_e *MockMetricsStorage_Expecter) GetMetrics(ctx interface{}, experimentID interface{}) *MockMetricsStorage_GetMetrics_Call {
	return &MockMetricsStorage_GetMetrics_Call{Call: _e.mock.On("GetMetrics", ctx, experimentID)}
}

func (_c *MockMetricsStorage_GetMetrics_Call) Run(run func(ctx context.Context, experimentID uuid.UUID)) *MockMetricsStorage_GetMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockMetricsStorage_GetMetrics_Call) Return(_a0 []analytics.VariantMetrics, _a1 error) *MockMetricsStorage_GetMetrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMetricsStorage_GetMetrics_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]analytics.VariantMetrics, error)) *MockMetricsStorage_GetMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMetricsStorage creates a new instance of MockMetricsStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsStorage {
	mock := &MockMetricsStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
