// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	event "github.com/drakoRRR/ab-test-system/apps/ab-test-system/backend/internal/domain/event"
)

// MockEventService is an autogenerated mock type for the EventService type
type MockEventService struct {
	mock.Mock
}

type MockEventService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventService) EXPECT() *MockEventService_Expecter {
	return &MockEventService_Expecter{mock: &_m.Mock}
}

// Ingest provides a mock function with given fields: ctx, events
func (_m *MockEventService) Ingest(ctx context.Context, events []event.Event) error {
	ret := _m.Called(ctx, events)

	if len(ret) == 0 {
		panic("no return value specified for Ingest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []event.Event) error); ok {
		r0 = rf(ctx, events)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventService_Ingest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ingest'
type MockEventService_Ingest_Call struct {
	*mock.Call
}

// Ingest is a helper method to define mock.On call
//   - ctx context.Context
//   - events []event.Event
func (_e *MockEventService_Expecter) Ingest(ctx interface{}, events interface{}) *MockEventService_Ingest_Call {
	return &MockEventService_Ingest_Call{Call: _e.mock.On("Ingest", ctx, events)}
}

func (_c *MockEventService_Ingest_Call) Run(run func(ctx context.Context, events []event.Event)) *MockEventService_Ingest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]event.Event))
	})
	return _c
}

func (_c *MockEventService_Ingest_Call) Return(_a0 error) *MockEventService_Ingest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventService_Ingest_Call) RunAndReturn(run func(context.Context, []event.Event) error) *MockEventService_Ingest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventService creates a new instance of MockEventService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventService {
	mock := &MockEventService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
