// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	sdk "github.com/drakoRRR/ab-test-system/apps/ab-test-system/backend/internal/domain/sdk"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetConfig provides a mock function with given fields: ctx, projectID
func (_m *MockService) GetConfig(ctx context.Context, projectID uuid.UUID) (sdk.Config, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 sdk.Config
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (sdk.Config, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) sdk.Config); ok {
		r0 = rf(ctx, projectID)
	} else {
		r0 = ret.Get(0).(sdk.Config)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type MockService_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
func (_e *MockService_Expecter) GetConfig(ctx interface{}, projectID interface{}) *MockService_GetConfig_Call {
	return &MockService_GetConfig_Call{Call: _e.mock.On("GetConfig", ctx, projectID)}
}

func (_c *MockService_GetConfig_Call) Run(run func(ctx context.Context, projectID uuid.UUID)) *MockService_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_GetConfig_Call) Return(_a0 sdk.Config, _a1 error) *MockService_GetConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetConfig_Call) RunAndReturn(run func(context.Context, uuid.UUID) (sdk.Config, error)) *MockService_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
