// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	experiment "github.com/drakoRRR/ab-test-system/apps/ab-test-system/backend/internal/domain/experiment"

	uuid "github.com/google/uuid"
)

// MockExperimentLister is an autogenerated mock type for the ExperimentLister type
type MockExperimentLister struct {
	mock.Mock
}

type MockExperimentLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExperimentLister) EXPECT() *MockExperimentLister_Expecter {
	return &MockExperimentLister_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: ctx, projectID
func (_m *MockExperimentLister) List(ctx context.Context, projectID uuid.UUID) ([]experiment.Experiment, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []experiment.Experiment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]experiment.Experiment, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []experiment.Experiment); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]experiment.Experiment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExperimentLister_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockExperimentLister_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
func (_e *MockExperimentLister_Expecter) List(ctx interface{}, projectID interface{}) *MockExperimentLister_List_Call {
	return &MockExperimentLister_List_Call{Call: _e.mock.On("List", ctx, projectID)}
}

func (_c *MockExperimentLister_List_Call) Run(run func(ctx context.Context, projectID uuid.UUID)) *MockExperimentLister_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockExperimentLister_List_Call) Return(_a0 []experiment.Experiment, _a1 error) *MockExperimentLister_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExperimentLister_List_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]experiment.Experiment, error)) *MockExperimentLister_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExperimentLister creates a new instance of MockExperimentLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExperimentLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExperimentLister {
	mock := &MockExperimentLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
