// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	apikey "github.com/drakoRRR/ab-test-system/apps/ab-test-system/backend/internal/domain/apikey"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, projectID, name
func (_m *MockService) Create(ctx context.Context, projectID uuid.UUID, name string) (apikey.Key, string, error) {
	ret := _m.Called(ctx, projectID, name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 apikey.Key
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (apikey.Key, string, error)); ok {
		return rf(ctx, projectID, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) apikey.Key); ok {
		r0 = rf(ctx, projectID, name)
	} else {
		r0 = ret.Get(0).(apikey.Key)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) string); ok {
		r1 = rf(ctx, projectID, name)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, string) error); ok {
		r2 = rf(ctx, projectID, name)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
//   - name string
func (_e *MockService_Expecter) Create(ctx interface{}, projectID interface{}, name interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, projectID, name)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, projectID uuid.UUID, name string)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockService_Create_Call) Return(_a0 apikey.Key, _a1 string, _a2 error) *MockService_Create_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (apikey.Key, string, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, projectID
func (_m *MockService) List(ctx context.Context, projectID uuid.UUID) ([]apikey.Key, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []apikey.Key
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]apikey.Key, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []apikey.Key); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]apikey.Key)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
func (_e *MockService_Expecter) List(ctx interface{}, projectID interface{}) *MockService_List_Call {
	return &MockService_List_Call{Call: _e.mock.On("List", ctx, projectID)}
}

func (_c *MockService_List_Call) Run(run func(ctx context.Context, projectID uuid.UUID)) *MockService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_List_Call) Return(_a0 []apikey.Key, _a1 error) *MockService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_List_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]apikey.Key, error)) *MockService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, projectID, keyID
func (_m *MockService) Revoke(ctx context.Context, projectID uuid.UUID, keyID uuid.UUID) error {
	ret := _m.Called(ctx, projectID, keyID)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, projectID, keyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockService_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
//   - keyID uuid.UUID
func (_e *MockService_Expecter) Revoke(ctx interface{}, projectID interface{}, keyID interface{}) *MockService_Revoke_Call {
	return &MockService_Revoke_Call{Call: _e.mock.On("Revoke", ctx, projectID, keyID)}
}

func (_c *MockService_Revoke_Call) Run(run func(ctx context.Context, projectID uuid.UUID, keyID uuid.UUID)) *MockService_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_Revoke_Call) Return(_a0 error) *MockService_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Revoke_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockService_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
