// Package sdkapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package sdkapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for SDKEventType.
const (
	Conversion SDKEventType = "conversion"
	Exposure   SDKEventType = "exposure"
)

// Defines values for SDKFlagRuleType.
const (
	Percentage SDKFlagRuleType = "percentage"
)

// Error defines model for Error.
type Error struct {
	Code      *string                 `json:"code,omitempty"`
	Details   *map[string]interface{} `json:"details,omitempty"`
	Message   *string                 `json:"message,omitempty"`
	Timestamp *time.Time              `json:"timestamp,omitempty"`
}

// SDKConfig defines model for SDKConfig.
type SDKConfig struct {
	Experiments []SDKExperiment    `json:"experiments"`
	Flags       []SDKFlag          `json:"flags"`
	ProjectId   openapi_types.UUID `json:"projectId"`
}

// SDKEvent defines model for SDKEvent.
type SDKEvent struct {
	ExperimentId openapi_types.UUID `json:"experimentId"`
	Id           openapi_types.UUID `json:"id"`

	// Name Event name, required for conversion events
	Name      *string      `json:"name,omitempty"`
	Timestamp time.Time    `json:"timestamp"`
	Type      SDKEventType `json:"type"`
	UserId    string       `json:"userId"`

	// Value Optional numeric value (e.g. revenue)
	Value     *float32           `json:"value,omitempty"`
	VariantId openapi_types.UUID `json:"variantId"`
}

// SDKEventBatch defines model for SDKEventBatch.
type SDKEventBatch struct {
	Events []SDKEvent `json:"events"`
}

// SDKEventType defines model for SDKEventType.
type SDKEventType string

// SDKExperiment defines model for SDKExperiment.
type SDKExperiment struct {
	Id             openapi_types.UUID `json:"id"`
	Key            string             `json:"key"`
	TrafficPercent float32            `json:"trafficPercent"`
	Variants       []SDKVariant       `json:"variants"`
}

// SDKFlag defines model for SDKFlag.
type SDKFlag struct {
	Enabled bool               `json:"enabled"`
	Id      openapi_types.UUID `json:"id"`
	Key     string             `json:"key"`
	Rules   []SDKFlagRule      `json:"rules"`
}

// SDKFlagRule defines model for SDKFlagRule.
type SDKFlagRule struct {
	Type  SDKFlagRuleType `json:"type"`
	Value float32         `json:"value"`
}

// SDKFlagRuleType defines model for SDKFlagRule.Type.
type SDKFlagRuleType string

// SDKVariant defines model for SDKVariant.
type SDKVariant struct {
	Id     openapi_types.UUID `json:"id"`
	Key    string             `json:"key"`
	Weight int                `json:"weight"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// PostSdkEventsJSONRequestBody defines body for PostSdkEvents for application/json ContentType.
type PostSdkEventsJSONRequestBody = SDKEventBatch

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Fetch project config for local evaluation
	// (GET /sdk/config)
	GetSdkConfig(w http.ResponseWriter, r *http.Request)
	// Ingest a batch of events
	// (POST /sdk/events)
	PostSdkEvents(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetSdkConfig operation middleware
func (siw *ServerInterfaceWrapper) GetSdkConfig(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSdkConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostSdkEvents operation middleware
func (siw *ServerInterfaceWrapper) PostSdkEvents(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostSdkEvents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/sdk/config", wrapper.GetSdkConfig).Methods("GET")

	r.HandleFunc(options.BaseURL+"/sdk/events", wrapper.PostSdkEvents).Methods("POST")

	return r
}

type BadRequestJSONResponse Error

type UnauthorizedJSONResponse Error

type GetSdkConfigRequestObject struct {
}

type GetSdkConfigResponseObject interface {
	VisitGetSdkConfigResponse(w http.ResponseWriter) error
}

type GetSdkConfig200JSONResponse SDKConfig

func (response GetSdkConfig200JSONResponse) VisitGetSdkConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSdkConfig401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetSdkConfig401JSONResponse) VisitGetSdkConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostSdkEventsRequestObject struct {
	Body *PostSdkEventsJSONRequestBody
}

type PostSdkEventsResponseObject interface {
	VisitPostSdkEventsResponse(w http.ResponseWriter) error
}

type PostSdkEvents202Response struct {
}

func (response PostSdkEvents202Response) VisitPostSdkEventsResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type PostSdkEvents400JSONResponse struct{ BadRequestJSONResponse }

func (response PostSdkEvents400JSONResponse) VisitPostSdkEventsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostSdkEvents401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PostSdkEvents401JSONResponse) VisitPostSdkEventsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Fetch project config for local evaluation
	// (GET /sdk/config)
	GetSdkConfig(ctx context.Context, request GetSdkConfigRequestObject) (GetSdkConfigResponseObject, error)
	// Ingest a batch of events
	// (POST /sdk/events)
	PostSdkEvents(ctx context.Context, request PostSdkEventsRequestObject) (PostSdkEventsResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetSdkConfig operation middleware
func (sh *strictHandler) GetSdkConfig(w http.ResponseWriter, r *http.Request) {
	var request GetSdkConfigRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSdkConfig(ctx, request.(GetSdkConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSdkConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSdkConfigResponseObject); ok {
		if err := validResponse.VisitGetSdkConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostSdkEvents operation middleware
func (sh *strictHandler) PostSdkEvents(w http.ResponseWriter, r *http.Request) {
	var request PostSdkEventsRequestObject

	var body PostSdkEventsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostSdkEvents(ctx, request.(PostSdkEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSdkEvents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostSdkEventsResponseObject); ok {
		if err := validResponse.VisitPostSdkEventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RXS2/jNhD+K8K0hxZQbGW3J92SJlsEOTTYbHsJcqCpkcy1+CgfbtxA/70YSoolS3l4",
	"kZxiipzH98035OQRuJZGK1TeQf4IFp3RymFcnLPiK/4T0Hlaca08qviTGVMLzrzQavndaUXfHF+jZPTr",
	"Z4sl5PDTcu962e665aW12kLTNCkU6LgVhpxATrES2wVrUvhLseDX2or/sPj44KNotN1ZkMPWKH8EY7VB",
	"60XLDdcF0l+/Mwg5OG+FqiB69kzU8QwrCkERWH0zsPU2YNrb6dV35BGxROdYNe/TC4nOM2lot9RWMg85",
	"FMzjCW1BemjSzAS4vbj+XatSVFMw+GDQCtmLQHiU7jUyby+uL5/MYB+QWct2tC5rVh3l7kvNqjlHxmrC",
	"cFWM0IcgilngpCJhSTZ3A9M+n3QE9n6ep8ttp7XnaHpTLimItx1TTMa6j0UZk0hoL016TEmpbcK12qJ1",
	"QqsEtxFG+g6S6T+8XnWK+Y3ONikEh7YlY+Juy+owA+tP07ZEooJEK3gSzyW/4KJaJJYABfyVytXnXNaa",
	"+X2+KsgV2jaAFUz9kC7ikS73dFzXod/OzZDNlxRzzjxfz8hme3RjbbuekuzhqrU5zbIsBSlUvz7skwOE",
	"XdCX0v3W1RtVkNHkwWgXLOHdS2zgYV/ace9PAL9R9hvctV3FpKlpi6+Rb3TwJyuvTvZFmdWqZWUp+A1a",
	"3qXwZr0cVYm/W5vptTQnKAI0SW0Q95lixHtvqhrFVjUOW2uldY1MHXGxvMBw8F6rORsbajz62v4aajyG",
	"ox5cH+4FZqLrCTv+QLumZZse0DnBPt1Fkj0ISSanXTu1q2wil4Pcu3ug9fNMtr1W3q8ftPJW13Nn/0VR",
	"rf1AHEJ5rGYSH5De2UyzJxuhSh3dCR9j315cJ1IXRH4K/V2Qw+kiW2SUgDaomBGQw+dFtvgMKRjm1xHu",
	"0hWbJX8aNSqMeRIhcWij+xr+QH9bbLp5JB2PnZ+y7N1Gvv3QMzP23bTTQdLmmjjFjFvrWM7fstPnXD/l",
	"upyOjciDFX4H+d0jnBlxjbuz4NeQ39039ym4ICWzO8jhC3q+Tsw4Pr3tteasTpB0FuFS7eMYdQeu2MA9",
	"RYn87h8Vo90MwTfaEcOX/YDQzdbnuti9J7mDd68ZS4/G3GZS2U/TgeCMczSeGCTas9dpH/xb8vGVulIV",
	"Op+wZEUgE10OZq5xYZrm/wAAAP//Rs09pU0NAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
